name: Build macOS .dmg

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build .dmg
        run: npm run dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: patient-dashboard-dmg
          path: dist/*.dmg
