name: Build App (macOS and Windows)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build for macOS
        run: npm run dist

      - name: Upload DMG file
        uses: actions/upload-artifact@v2
        with:
          name: macos-dmg
          path: dist/*.dmg

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        run: npm run dist

      - name: Upload EXE file
        uses: actions/upload-artifact@v2
        with:
          name: windows-exe
          path: dist/*.exe
